// This files manages the logic for making a pull request to the repo containing the .htacces needed to redirect.

const octokit = require('@octokit/rest')()

export function createPullRequest(owner:string, repo:string, head: string, token:string){
    authenticate(token) //this should be extracted to higher lying function later
    octokit.pullRequests.create({
    owner : "oSoc18", 
    repo  : "resolver",
    title : "please pull me in", 
    head  : "BertSchoovaerts:master", 
    body  : generateBody(),
    base  : "master" }, (error:any ,result:any) => {
        console.log("result: " + result)
        console.log("error: " + error)
    })
}

function generateBody():string{
    var result:string = ""
    result += "Automated pullRequest generated by resolver application @" + new Date() +". /n"
    result += "Reqested by *****username*****"
    result += "Update of *****csv-filename*****"

    return result
}
function authenticate(token: string) :void {
    octokit.authenticate({
        type: "oauth",
        token: token
    })
}

export function createFork(owner: string, repo: string, token:string){
authenticate(token)
octokit.repos.fork({
    owner : "oSoc18",
    repo  : "resolver"
}, (error:any, result:any) => {
    console.log(result)
    console.log("error: " + error)
})
}