// This file contains configuration information for culturize

// This class contains the default values for the fields
// in the main menu
export class fieldDefaults
{
    // Basic fields
    static subdir = "";
    static repo = "";

    // "Advanced" fields
    static branch = "master";
    static commitMessage = "Culturize Import";
    static pullrequestTitle = "Culturize Import";
    static pullrequestBody = "This pull request was automatically generated by the Culturize App"
}