// This file contains configuration information for Culturize

// This class contains the default values for the fields
// in the main menu
export class PublishFormDefaults
{
    // Subdirs:
    // The final subdir where the files are going to be
    // saved is made of forcedSubdir + subDir. 
    // Leaving it empty will make the app push/save everything to the root
    // of the repo.
    // The ForcedSubdir is also invisible to the user, and is added
    // at the publishing stage by the publish() function in Publishing.ts.

    // If you decide to add a default value for subDir, don't forget
    // to end it with "/".
    // Example values: foo/, foo/bar/
    // Always test changes made to the forcedSubdir, because typos can easily
    // create errors for the end user.
    static subdir = "";
    static forcedSubdir = ""; 

    // Default value for the repo field.
    static repo = "";

    // "Advanced" fields
    static branch = "master";

    static commitMessage = "Culturize Import";
    static pullrequestTitle = "Culturize Import";
    static pullrequestBody = "This pull request was automatically generated by the Culturize App"
}

// Api Conf: secret & id
export class APIConf {
    static clientID = ""; // Your client ID
    static clientSecret = ""; // Your client secret
}

// CSV File Configuration
export class CSVConf {
    // The name of the column which contains the identifier
    static COL_PID = "PID";

    // The name of the column which contains the URL
    static COL_URL = "URL";

    // The name of the (optional) column which contains a number 
    // (0/1 -> true/false) to enabled/disable the rule
    static COL_ENABLED = "enabled";

    // The name of the column which contains the document type
    static COL_DOCTYPE = "document type";
}